### ISSUE TITLE
Make ProcalParser independant from using RJM's BigDecimalMath package

### ISSUE THREAD

**Issue by danvim** [ProcalApp/ProcalParser#14]
The BigDecimalMath package has several disadvantages to the project, including:

- Under-optimal trigonometry computational time
- Redundant functionalities in the package
- Inaccuracy in our methods of usages
- Restrictive GNU license

With the above concerns, it is necessary to implement our own methods in our own calculation package and be independent from using RJM's BigDecimalMath package.

---

### TODO List:

- [x] Found custom Big Decimal mathematics library under `calc` package.
- [x] Implement taylor series expansion function and trig functions
- [ ] Implement a better way of doing trigonometric functions and other functions involving Taylor series.
- [ ] Angle tables for trigonometric functions (issue #13)
